### ISSUE TITLE
Missing dependency definition - neither a requirements.txt nor a environment.yml

### ISSUE THREAD

**Issue by TommeTao** [apchenstu/mvsnerf#36]
Hi there,

May I kindly ask you to add a `requirements.txt` or `environment.yml` (with the later being prefered)? I am trying to get your code working and am running into multiple dependency issues, such as:

- module not found errors for at least three packages, e.g., `kornia`
- `ImportError` for `inplace_abn`, which might indicate an [incompatible PyTorch version](https://github.com/ternaus/TernausNetV2/issues/20) (`ImportError: /mvsnerf/conda-env-py37/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor3addEN3c106ScalarES2_`)

Highly appreciated if you run something like `conda env export --file environment.yml` from within the active conda environment and add the file to the repository.

Thanks a lot!

**Comment by codestella** [comment]
I agree. I faced same error... how can i fix it?

**Comment by codestella** [comment]
@TommeTao hello, did you fix the error? ImportError: /mvsnerf/conda-env-py37/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor3addEN3c106ScalarES2_

**Comment by peerschuett** [comment]
@codestella Your error appears, because you compiled some parts of your code (this case inplace_abn) with another pytorch version, than you use later on. This usually happens if you install packages that have a dependency for newer pytorch versions. 

What I did was checking which package installs the new pytorch version. In my case this was "kornia" and I needed to specify "pip install kornia==0.5.11".

The dependencies for MVSNeRF that I installed with pip are 
`pip install pytorch-lightning==1.3.5  inplace_abn  imageio pillow scikit-image opencv-python configargparse lpips kornia==0.5.11 warmup_scheduler
`
I hope that helps you!

**Comment by hengfei-wang** [comment]
Well, I used `pip install pytorch-lightning==1.3.5 inplace_abn imageio pillow scikit-image opencv-python configargparse lpips kornia==0.5.11 warmup_scheduler` to install packages. But I got 'The CUDA version(11.5) detected is not the one used to compile pytorch(10.5)' error when installing inpalce_abn. Sorry, I can't remember exact output message. I guess pytorch-ligntning installs one version of torch compiled by CUDA 10.2 and inplace_abn detects this version and tries to use it. But it found the local cuda version dismatch with torch version, so it reports the error. I reinstalled pytorch using `pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html` to solve this problem. 

Actually, I recommend to use anaconda to install packages in normal cases because conda is very good at managing dependies of different packages. However, there are some packages must be installed using pip in this project. Sad, I have to say using pip troubles me a lot.

**Comment by hengfei-wang** [comment]
Another reminder:

Remember to do 'pip install imageio-ffmpeg' if you want to rendering videos. 

Can authors check their code and make a good guideline? :-(

**Comment by sviperm** [comment]
Thanks @hengfei-wang for the tip. Thats problem with `inplace_abn` come from different cuda version of the system and cuda version of pytorch.

I tried to install pytorch + cudatoolkit==11.3 via conda, but in jupyter i had `torch.cuda.is_available() == False`

After installing all with pip works like a charm.

My installation process:

```shell
conda create -n mvsnerf python=3.8
conda activate mvsnerf
pip install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
pip install pytorch-lightning==1.3.5 imageio pillow scikit-image opencv-python configargparse lpips kornia warmup_scheduler matplotlib
```
Installing inplace_abn from [source](https://github.com/mapillary/inplace_abn#:~:text=git%20clone%20https%3A//github.com/mapillary/inplace_abn.git%0Acd%20inplace_abn%0Apython%20setup.py%20install%0Acd%20scripts%0Apip%20install%20%2Dr%20requirements.txt)
```shell
git clone https://github.com/mapillary/inplace_abn.git
cd inplace_abn
python setup.py install
```
---
Dear authors (@apchenstu), please check your repository and notebooks before you publish it, a lot of imports are missed, variables isn't initiated, no dependencies file and full installation requirements. Running just single file become challenging!

**Comment by elenacliu** [comment]
besides above, I found that:

1. torchmetrics==0.5.0 (otherwise error:
```
from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/anaconda3/envs/mvsnerf/lib/python3.8/site-packages/torchmetrics/utilities/data.py))
```
)
2. setuptools==59.5.0 (otherwise error:
```
AttributeError: module 'distutils' has no attribute 'version'
```
)
3. test-tube==0.7.5 (otherwise error:
```
Traceback (most recent call last):
  File "train_mvs_nerf_finetuning_pl.py", line 302, in <module>
    logger = loggers.TestTubeLogger(
  File "/home/anaconda3/envs/mvsnerf/lib/python3.8/site-packages/pytorch_lightning/loggers/test_tube.py", line 98, in __init__
    raise ImportError(
ImportError: You want to use `test_tube` logger which is not installed yet, install it with `pip install test-tube`.
```
)
4. pillow==9.5.0 (otherwise error:
```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
)
